### ISSUE TITLE
stbx-tx-store: Create Firestore backend

### ISSUE THREAD

**Issue by epost** [statebox/purescript-studio#231]
The in-memory version should be replaced by one that works with out cloud Firebase/Firestore, and do so through an abstraction.

## todo

- [ ] Implement storing of transactions
- [ ] Implement storing of execution states. (Should perhaps be a separate issue)
- [ ] Test on pulumi?

## references

- memory implementation: [Memory.purs](https://github.com/statebox/purescript-studio/blob/25f1db6f95a9d6c6fe418c9efd7b298bdbd419a7/stbx-tx-store/src/Statebox/TransactionStore/Memory.purs#L25-L30)
- [get/put tx algebra](https://github.com/statebox/purescript-studio/blob/development/stbx-tx-store/src/Statebox/TransactionStore/Types.purs#L23)
- trace through js:
  - https://github.com/statebox/cloud/blob/66b7c98a0939e3ac6577d235cf8b79f88d0fb505/services/tx/process-tx.js#L6-L33
  - https://github.com/statebox/cloud/blob/66b7c98a0939e3ac6577d235cf8b79f88d0fb505/services/tx/process-tx.js#L38-L50
  - https://github.com/statebox/cloud/blob/66b7c98a0939e3ac6577d235cf8b79f88d0fb505/services/tx/process-tx.js#L17-L20
