### ISSUE TITLE
Fix broken build

### ISSUE THREAD

**Issue by epost** [statebox/purescript-studio#239]
# TODO
- [x] Tx `Codec` compilation error
  ```
  in module Test.Statebox.Core.Transaction.Codec
    at test/Statebox/Core/Transaction/Codec.purs:18:41 - 18:52 (line 18, column 41 - line 18, column 52)

  Cannot import value decodeTxSum from module Statebox.Core.Transaction.Codec
  It either does not exist or the module does not export it.
  ```
- [x] Spago package set versions are mixed 0.12 and 0.13
  - [x] revise these todos; it turns out we have a central `/packages.dhall` now, but it seems like there is just a lot of stuff referencing 0.12 still around that needs to be cleaned up.
    - [x] `upstream`s should now probably point to `/packages.dhall` (-> #198)
  - [x] upgrade Spago versions to 0.9.0
  - [x] upgrade `purescript` versions to 0.13.3 everywhere.
  - [x] eliminate `mkPackage`, see https://github.com/spacchetti/spago/pull/301
    - [x] replace references to `mkPackage` of purescript-halogen-svg by new syntax (in `studio/`, `halogen-petrinet-editor/`)
  - [x] upgrade package set versions in `**/packages.dhall` to
    ```dhall
    let upstream =
          https://github.com/purescript/package-sets/releases/download/psc-0.13.3-20190818/packages.dhall sha256:c95c4a8b8033a48a350106b759179f68a695c7ea2208228c522866fd43814dc8
    ```

# Details
## mixed package set versions

these have been updated to 0.13:
```
$ fd packages.dhall | xargs ag "0.13"
halogen-petrinet-editor/packages.dhall
5:      https://github.com/purescript/package-sets/releases/download/psc-0.13.3-20190818/packages.dhall sha256:c95c4a8b8033a48a350106b759179f68a695c7ea2208228c522866fd43814dc8

halogen-petrinet-editor-example/packages.dhall
5:      https://github.com/purescript/package-sets/releases/download/psc-0.13.3-20190818/packages.dhall sha256:c95c4a8b8033a48a350106b759179f68a695c7ea2208228c522866fd43814dc8

halogen-tree-menu/packages.dhall
5:      https://github.com/purescript/package-sets/releases/download/psc-0.13.3-20190818/packages.dhall sha256:c95c4a8b8033a48a350106b759179f68a695c7ea2208228c522866fd43814dc8

studio/packages.dhall
5:      https://github.com/purescript/package-sets/releases/download/psc-0.13.3-20190818/packages.dhall sha256:c95c4a8b8033a48a350106b759179f68a695c7ea2208228c522866fd43814dc8

studio-common/packages.dhall
2:      https://github.com/purescript/package-sets/releases/download/psc-0.13.3-20190818/packages.dhall sha256:c95c4a8b8033a48a350106b759179f68a695c7ea2208228c522866fd43814dc8
```
and these are 0.12:
```
$ fd packages.dhall | xargs ag "0.12"
halogen-petrinet-editor/packages.dhall
2:      https://raw.githubusercontent.com/purescript/package-sets/psc-0.12.5-20190427/src/mkPackage.dhall sha256:0b197efa1d397ace6eb46b243ff2d73a3da5638d8d0ac8473e8e4a8fc528cf57

halogen-petrinet-editor-example/packages.dhall
2:      https://raw.githubusercontent.com/purescript/package-sets/psc-0.12.5-20190427/src/mkPackage.dhall sha256:0b197efa1d397ace6eb46b243ff2d73a3da5638d8d0ac8473e8e4a8fc528cf57

halogen-tree-menu/packages.dhall
2:      https://raw.githubusercontent.com/purescript/package-sets/psc-0.12.5-20190508/src/mkPackage.dhall sha256:0b197efa1d397ace6eb46b243ff2d73a3da5638d8d0ac8473e8e4a8fc528cf57

pnpro/packages.dhall
2:      https://raw.githubusercontent.com/purescript/package-sets/psc-0.12.5-20190427/src/mkPackage.dhall sha256:0b197efa1d397ace6eb46b243ff2d73a3da5638d8d0ac8473e8e4a8fc528cf57
5:      https://raw.githubusercontent.com/purescript/package-sets/psc-0.12.5-20190427/src/packages.dhall sha256:6b17811247e1f825034fa4dacc4b8ec5eddd0e832e0e1579c2ba3b9b2a1c63fe

stbx-client-rest/packages.dhall
112:      https://raw.githubusercontent.com/purescript/package-sets/psc-0.12.5-20190508/src/mkPackage.dhall sha256:0b197efa1d397ace6eb46b243ff2d73a3da5638d8d0ac8473e8e4a8fc528cf57
115:      https://raw.githubusercontent.com/purescript/package-sets/psc-0.12.5-20190508/src/packages.dhall sha256:8ef3a6d6d123e05933997426da68ef07289e1cbbdd2a844b5d10c9159deef65a

stbx-core/packages.dhall
112:      https://raw.githubusercontent.com/purescript/package-sets/psc-0.12.5-20190427/src/mkPackage.dhall sha256:0b197efa1d397ace6eb46b243ff2d73a3da5638d8d0ac8473e8e4a8fc528cf57
115:      https://raw.githubusercontent.com/purescript/package-sets/psc-0.12.5-20190427/src/packages.dhall sha256:6b17811247e1f825034fa4dacc4b8ec5eddd0e832e0e1579c2ba3b9b2a1c63fe

stbx-example-data/packages.dhall
2:  https://raw.githubusercontent.com/purescript/package-sets/psc-0.12.5-20190508/src/mkPackage.dhall sha256:0b197efa1d397ace6eb46b243ff2d73a3da5638d8d0ac8473e8e4a8fc528cf57
5:  https://raw.githubusercontent.com/purescript/package-sets/psc-0.12.5-20190508/src/packages.dhall sha256:8ef3a6d6d123e05933997426da68ef07289e1cbbdd2a844b5d10c9159deef65a

stbx-service-rest/packages.dhall
2:      https://raw.githubusercontent.com/purescript/package-sets/psc-0.12.5-20190508/src/mkPackage.dhall sha256:0b197efa1d397ace6eb46b243ff2d73a3da5638d8d0ac8473e8e4a8fc528cf57
5:      https://raw.githubusercontent.com/purescript/package-sets/psc-0.12.5-20190508/src/packages.dhall sha256:8ef3a6d6d123e05933997426da68ef07289e1cbbdd2a844b5d10c9159deef65a

studio/packages.dhall
2:      https://raw.githubusercontent.com/purescript/package-sets/psc-0.12.5-20190427/src/mkPackage.dhall sha256:0b197efa1d397ace6eb46b243ff2d73a3da5638d8d0ac8473e8e4a8fc528cf57
```

## mixed Spago versions

```
$ fd package.json | xargs ag "\"spago\""
halogen-petrinet-editor/package.json
14:    "spago": "^0.9.0"

halogen-petrinet-editor-example/package.json
24:    "spago": "^0.9.0"

halogen-tree-menu/package.json
14:    "spago": "^0.9.0"

pnpro/package.json
18:    "spago": "^0.8.5"

stbx-client-rest/package.json
17:    "spago": "^0.8.5",

stbx-core/package.json
31:    "spago": "^0.8.5",

stbx-example-data/package.json
14:    "spago": "^0.8.5"

stbx-service-rest/package.json
20:    "spago": "^0.8.5"

studio/package.json
27:    "spago": "^0.9.0"```
