### ISSUE TITLE
studio: View wirings using kdmoncat brick diagram editor

### ISSUE THREAD

**Issue by sjoerdvisscher** [statebox/purescript-studio#257]
## todo

Prerequisite: #278

- [x] add purescript-kdmoncat as ~~dependency to~~ part of purescript-studio
- [x] expose the kdmoncat viewer in the studio UI

Erik's integration WIP notes:

- [x] integrate using git subtree
  - [x] add commits from Sjoerd's PR
    - [x] `d8e9279`: not needed, done by `git subtree`
    - [x] `cc1ca19`: put modules under `KDMonCat`
    - [x] `782d8c2`: breaks because it contains a commit for a safari fix  already imported from the `purescript-kdmoncat` repo
      - [x] manually edit patch and apply
    - [x] `b76445b`: tweak example data (absorbed into previous commit)
    - [x] `c8706f5`:  stbx-lang: Adapt diagram parser for use with the kdmoncat wiring viewer. 
    - [x] `b5dcc40`: studio: Move conversion of DiagramInfo to Operators to stbx-lang.
    - [x] `f6739d2`: fix whitespace
    - [x] `c9b9c5e`: refactor `fromOps` for clarity
    - [x] Erik's [`let`-to-`where` commit](https://github.com/statebox/purescript-studio/pull/293/commits/8cf8cdeb9e6ae3132b14405d5b6018ea988670e3) on top of the original PR 
- [x] Make sure `halogen-kdmoncat` project depends on the `vec` library from `/packages.dhall`
  - [x] Need `Ord (Vec3 Int)` 
    ```
    [1/1 NoInstanceFound] ./../halogen-kdmoncat/src/KDMonCat/Model.purs:121:20
  
      121            { accum: Map.insert fv next m, value: next }
                              ^^^^^^^^^^^^^
  
      No type class instance was found for
  
        Data.Ord.Ord (Vec3 Int)
    ```

## doc

- old brick diagrams spec: https://docs.statebox.org/spec/nlldiagrams/
- new brick diagrams spec (kdmoncat): https://docs.statebox.org/spec/brickdiagrams2/
- some code andrev wrote to process the old version, which is used to render the diagrams in the studio: https://github.com/statebox/purescript-studio/blob/development/studio/src/Data/Diagram/FromNLL.purs
