### ISSUE TITLE
halogen-diagram-editor: drag & drop on spacebar-created bricks destroys them 

### ISSUE THREAD

**Issue by clayrat** [statebox/purescript-studio#267]
Erik:

### cause
Cause: reload event in the studio overwrites the changed diagram with the loaded one from the studio state, hereabouts:

https://github.com/statebox/purescript-studio/blob/f214105a6b62b697008bedc61c3c8ae5b1d5c3bc/studio/src/View/Studio/View.purs#L84-L94

### todo
- [x] `Halogen.raise` an 'output event' that will allow us to respond to diagram edits.
- [x] Process this event and persist them, for loaded `Project`s.
- [x] get rid of [CursorMoved](https://github.com/statebox/purescript-studio/blob/development/halogen-diagram-editor/src/View/Diagram/DiagramEditor.purs#L78)
