### ISSUE TITLE
Convert wiring AST to Brick Diagrams v1 format

### ISSUE THREAD

**Issue by sjoerdvisscher** [statebox/purescript-studio#270]
## todo

- [x] Convert [ASTs roughly like this one](https://github.com/statebox/purescript-studio/blob/69b64c1f3df75aa015e13056a7164bc37e670988/stbx-lang/test/Wiring.purs#L23-L37) into brick diagrams.
- [x] ~~Add documentation (see the stuff below for example) to https://docs.statebox.org, e.g. [here](https://docs.statebox.org/spec/nlldiagrams/).~~ Covered by Marco's 'How we store diagrams' document.
- [ ] Add one or more test to check that the resulting `Statebox.Core.Types.Diagram`  matches the expected one.

## encoding

Erik: In the brick editor we can draw the following, but is it possible to encode this using a wiring tree? (??1!)
  ```
  -------------
  |     a     |
  -------------
  |  b  |  c  | 
  -------------
  |     d     |
  -------------
  ```

Jelle: why not? `a.output_1~b.input_1  a.o2~c.i1  b.o1~d.i1  c.o1~d.i2`
