### ISSUE TITLE
stbx-core: Compute and render folds over execution history

### ISSUE THREAD

**Issue by epost** [statebox/purescript-studio#307]
## todo

- [x] Get sequence of fired transitions from transaction history
- [ ] Compute folds over transaction history.
  - transaction hash
  - transition id
  - marking
  - running | valid | invalid
- [ ] Store this state at the corresponding (state) hash in an `AdjacencySpace`-based cache.
- [ ] Show them in the studio.
  - [ ] render wirings loaded from API transactions.
    - [ ] enable `RouteF` to point to arbitrary-length path of diagrams, optionally followed by a net.
    - [ ] convert from `Diagram` v1 to ...
    - [ ] solve the kinded id clicks issue so we can distinguish between a net and a wiring
      - [ ] why doesn't it seem to work when clicking on e.g. a (root?) node of an API-loaded diagram with a single net in it, like for the GUTS example net? I'd expect the net 'inside' the node to be shown, but it isn't.
      - [ ] visually render nested wirings... how?
  - [ ] Show glued markings in diagram editor.
  - [ ] Show glued markings in kdmoncat. -> #308
  - [ ] Show glued markings in Petri net editor somehow.

## why?

- needed in wiring and transaction explorer
- needed in inbox app
