### ISSUE TITLE
Refactor Wirings, Routes, Paths

### ISSUE THREAD

**Issue by epost** [statebox/purescript-studio#331]
## goals

1. Clarify and enforce separation between serialisation format and core data structures.
2. Make stbx-core data structures addressable in a well-typed way (paths, routes, etc).

## tasks
- [x] `Path` should be defined in `Statebox.Core.WiringTree`. (See also Marco's executions PR #334 for work on this.)
  - [x] ...or `Wiring.Tree` or whatever
- [x] Newtype the `labels` in `Wiring`; is now `Array Int`, should be `Array <some newtype>`
  - [x] introduce `Wiring` newtype vs. `WiringRaw`
  - [x] Split off module `Statebox.Core.Net` from `Statebox.Core.Types` 
  - [x] Split off module `Statebox.Core.Diagram` from `Statebox.Core.Types` 
  - [x] Split off module `Statebox.Core.Wiring` from `Statebox.Core.Types` 
    - [x] Introduce the `labels` newtype mentioned in parent task.
    - [x] Fix transaction codec breakage.
  - [x] Split off module `Statebox.Core.Firing` from `Statebox.Core.Types` 
  - [x] Split off module `Statebox.Core.Initial` from `Statebox.Core.Types` 
- [ ] `Statebox.Core.Types`
  - [x] Move all definitions from `Statebox.Core.Types` into submodules, and re-export them.
  - [ ] Get rid of explicit `Statebox.Core.Types` imports; use `Statebox.Core` instead?
  - [ ] Get rid of explicit `Statebox.Core.Types` module altogether?
- [ ] Dedupe and move types.
  - [x] `Singleton` should go into `Statebox.Core.Common.
  - [x] `Message` should go into `Statebox.Core.Common.
  - [x] `TxId` should go into `Statebox.Core.Common`.
  - [ ] `TxId` should be removed from `Statebox.Transaction` (duplication).
  - [x] `HexStr` should go into `Statebox.Core.Common`.
  - [ ] `HexStr` should be removed elsewhere.
  - [ ] `HashStr` (should go into `Statebox.Core.Common` instead of `Statebox.Transaction`).
  - [ ] Make sure `stbx-protocol/src/Statebox/Protocol/Fire.purs` doesn't have the duplicated `Marking` stuff (see [here](https://github.com/statebox/purescript-studio/pull/359/files#diff-656ded03cd98246ed2418b8d3078dd5bR64-R66)).
  - [ ] Make sure `Tokens`, `TransitionMarkingF`, `PlaceMarkingF` are not duplicated (see [here](https://github.com/statebox/purescript-studio/pull/334/files#diff-d28f623062a3b9cb8929e2918d36a914R19-R32)).
- [ ] Newtype all the things!
  - [ ] in `stbx-core` under `Statebox` or `Statebox.Core` look for `Ints`, `type` aliases, etc.
- [ ] Addressable Statebox API 'objects' (wirings, diagrams, nets, places, transitions, nets, execution states, etc.) should have their own address/path/route type.
- [ ] Studio `Route`s should be implemented in terms of these.
- [ ] the `findXXX` methods in `Studio.Model` should be split off and factored out into their own module; `Transaction.Cache` perhaps?
- [ ] Sjoerd: Should the `Operator` type also be in `Statebox.Core`? See https://github.com/statebox/purescript-studio/pull/326/commits/b591ca55ad13b1319276f65636765cfb336a3987
- [ ] ...
