### ISSUE TITLE
Look at CSS libs

### ISSUE THREAD

**Issue by epost** [statebox/purescript-studio#348]
## todo

- [x] check out tailwind
  - [x] check out tailwind as used in purescript-ocelot, the halogen components suite
- [x] check out hiq
  - [ ] make a proof of concept
- [x] check out bulma (see inbox-app, studio history)

## results

- tailwind
  - vanilla way sucks to use with modular purescript project
- hiq
  - Sjoerd likes it
  - uses CSS vars rather than SASS
  - has a [theme builder](https://hiq-theme-builder.netlify.com)
  - has a dark theme / light theme switch
- bulma
  - provides a lot of **standard** (and documented) markup and examples
