### ISSUE TITLE
studio: Deploy master and development versions separately

### ISSUE THREAD

**Issue by epost** [statebox/purescript-studio#379]
## todo

- [x] merge current `development` (a0d07cb2c69f7ac9889b9a5d3bc819e907c1bfdc) into `master`
- [x] edit: deploy `edit.statebox.cloud` on Netlify from `master`
- [x] tx-browser: deploy `browse.statebox.cloud` from `master`
- [x] studio: deploy `studio.statebox.cloud` on Netlify from `master`

## links

- netlify build settings admin:
  - studio: https://app.netlify.com/sites/statebox-studio-test/settings/deploys
  - tx browser: https://app.netlify.com/sites/dazzling-albattani-1c9272/settings/deploys
  - edit: https://app.netlify.com/sites/cranky-goldstine-6a507b/settings/deploys
